version: "3.9"
services:
  service1:
    build:
      context: ./service1
      target: base
    ports:
      - 5678:5678
    runtime: nvidia
    environment:
      TF_XLA_FLAGS: --tf_xla_enable_xla_devices
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
  service2:
    build:
      context: ./service2
      target: base
    ports:
      - 5679:5678
    runtime: nvidia
    environment:
      TF_XLA_FLAGS: --tf_xla_enable_xla_devices
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
